<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>False</SignAssembly>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>MeteorTools</Title>
    <Authors>悠静萝莉</Authors>
    <Description>一个个人常用功能整合包</Description>
    <PackageProjectUrl>https://github.com/timi137137/MeteorTools</PackageProjectUrl>
    <RepositoryUrl>https://github.com/timi137137/MeteorTools</RepositoryUrl>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <PackageLicenseFile>License.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <PackageIcon>MeteorToolsicon.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <Copyright>悠静萝莉 Copyright 2019-2025</Copyright>
    <PackageTags>Tools MeteorTools mikuhl</PackageTags>
    <PackageReleaseNotes>Refactor and migrate to.NET 8</PackageReleaseNotes>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>D:\Data\Programme\CSharp\MeteorTools\MeteorTools.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="License.txt" />
    <None Remove="MeteorToolsicon.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="License.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </EmbeddedResource>
    <EmbeddedResource Include="MeteorToolsicon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </EmbeddedResource>
  </ItemGroup>

</Project>
